"""
Deploy with `firebase deploy`

Note: This whole functions folder was auto-generated by running `firebase init functions`
"""

# cloud functions for firebase
from firebase_functions import https_fn
# firebase admin module to access cloud firestore things
from firebase_admin import firestore, initialize_app

import google.cloud.firestore
import requests

# define magic strings here for now
TEXT_KEY = 'text'

firebase_app = initialize_app()

@https_fn.on_request()
def find_by_text_search(req: https_fn.Request) -> https_fn.Response:
    """Fetches place by Google Places API text-search

    See more here
    https://developers.google.com/maps/documentation/places/web-service/text-search

    Args: TODO
    Returns: TODO
    Raises: TODO
    """

    query = req.args.get(TEXT_KEY)
    if query is None:
        return https_fn.Response("No text query provided", status=400)

    firestore_client: google.cloud.firestore.Client = firestore.client()

    return https_fn.Response("Not yet implemented.")
