// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWGfa5UnA6iDe42S_-4sgbP7uOfckrWo4',
    appId: '1:484287344456:web:75d448343d0e3d66890d7d',
    messagingSenderId: '484287344456',
    projectId: 'chews-org',
    authDomain: 'chews-org.firebaseapp.com',
    storageBucket: 'chews-org.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf94-rH5P0C-K7Ws8rizAvkmCp-_b0oHE',
    appId: '1:484287344456:android:444025a5e4881597890d7d',
    messagingSenderId: '484287344456',
    projectId: 'chews-org',
    storageBucket: 'chews-org.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGu5VGmG8lBg5_1yxC_WrcY1-OpSF3hYs',
    appId: '1:484287344456:ios:16bdf22459f2bdbc890d7d',
    messagingSenderId: '484287344456',
    projectId: 'chews-org',
    storageBucket: 'chews-org.appspot.com',
    iosClientId: '484287344456-bu5r920fj6rfh5efljh72lg1i1rbl369.apps.googleusercontent.com',
    iosBundleId: 'com.example.chews',
  );
}
