// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdHjNQFIwtCGW0_qfEyQcQu0e_J6jUDKQ',
    appId: '1:837798840636:web:7f2fb05d03bf77a5efb639',
    messagingSenderId: '837798840636',
    projectId: 'chews-2ba9e',
    authDomain: 'chews-2ba9e.firebaseapp.com',
    storageBucket: 'chews-2ba9e.appspot.com',
    measurementId: 'G-Q0GSTHNM6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2OCIxx688eQ5WhIR9n-bvUuaNe_rs8tk',
    appId: '1:837798840636:android:f7fae84d0b93cc21efb639',
    messagingSenderId: '837798840636',
    projectId: 'chews-2ba9e',
    storageBucket: 'chews-2ba9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN3dMuLGfgPjjky6oJMNB3OaA75yDBiyA',
    appId: '1:837798840636:ios:c0ebfdafb603f2fcefb639',
    messagingSenderId: '837798840636',
    projectId: 'chews-2ba9e',
    storageBucket: 'chews-2ba9e.appspot.com',
    iosBundleId: 'com.example.chews',
  );

}